### PR TITLE
MongoDataset for reading text classification data from a Mongo database

### PR DESCRIPTION
**Pull request by carljohanrehn**
This is my second pull request ever on GitHub. I hope it works this time!

I have implemented a MongoDataset class in Flair for reading text classification data from a Mongo database collection using queries.

The following simple example shows how the MongoDataset class could be used:

query = {'Län': "Stockholms län"}

kwargs = {
'host': 'localhost',
'port': 27017,
'database': 'rosenberg',
'collection': 'book',
'text_field': 'Beskrivning',
'categories_field': ['Län', 'Härad', 'Tingslag', 'Församling', 'Plats']
}

train_dataset: MongoDataset = MongoDataset(query, **kwargs)

### CODE REVIEW

**Comment by alanakbik** [comment]
Hi @carljohanrehn thanks for adding this. I'm not sure how to test this from my side though. Could you provide some instructions on how to set up and use this? This would also help other users to use this feature!

**Comment by carljohanrehn** [comment]
If you think there is an interest in having this feature I can write down some instructions on how to set up Mongo DB and upload data to it. After that it's really a piece of cake to create a MongoDataset in Flair. 

Let me know if your really like to have this feature!

**Comment by alanakbik** [comment]
Yes, some instructions would be great! Thanks!

**Comment by yosipk** [comment]
👍

**Comment by carljohanrehn** [comment]
### How to create classification data in Mongo DB

Let us use the 20 Newsgroups data set, see http://qwone.com/~jason/20Newsgroups/.

I followed the procedure described in https://scikit-learn.org/stable/tutorial/text_analytics/working_with_text_data.html for downloading and extracting the data.

Here is a short piece of code, which shows how to create a list of records for a selected set of Newsgroups data. 

```
import pandas as pd

categories = ['alt.atheism', 'soc.religion.christian', 'comp.graphics', 'sci.med']

from sklearn.datasets import fetch_20newsgroups

twenty_train = fetch_20newsgroups(subset='train', categories=categories, shuffle=True, random_state=42)

df = pd.DataFrame(zip((twenty_train.target_names[_] for _ in twenty_train.target), twenty_train.data), columns=('category', 'text'))
# df.head()

records = df.to_dict(orient='records')
```

Make sure you have access to a running instance of Mongo DB server. I use  Docker for Mongo, see https://hub.docker.com/_/mongo. You can start the server by issuing

`docker run -d mongo
`

Now, let's use PyMongo, see https://api.mongodb.com/python/current/, for inserting our Newsgroups records into Mongo DB.

```
import pymongo

client = pymongo.MongoClient("mongodb://localhost:27017/")
database = client['flair']
collection = database['newsgroups']

results = collection.insert_many(records)
print(results)

collection.count()

for document in collection.find():
    print(document)
    break
```

Allright, the hard work is done. We have stored our classification data in a Mongo "flair" database and the collection "newsgroups". 

Our final step is to  create a MongoDataset in Flair. This is really easy, 

```
from flair.datasets import MongoDataset

wargs = {
    'host': 'localhost',
    'port': 27017,
    'database': 'flair',
    'collection': 'newsgroups',
    'text_field': 'text',
     'categories_field': ['category']
}

query = {'category': 'comp.graphics'}
# query = {'category': {'$in': ['alt.atheism', 'soc.religion.christian', 'comp.graphics', 'sci.med']}}

train_dataset: MongoDataset = MongoDataset(query, **kwargs)

train_dataset.categories
# ['category']

train_dataset.total_sentence_count
# 584

sents = train_dataset.sentences

sents[0]
# Sentence: "From : sd345 @ city.ac.uk ( Michael Collier ) Subject : Converting images to HP LaserJet III ? Nntp-Posting-Host : hampton Organization : The City ... ." - 125 Tokens

sents[0].labels
# [comp.graphics (1.0)]
```

**Comment by carljohanrehn** [comment]
I hope the instruction is "readable".

I have not tried to serialize the MongoDataset class. Please, try it out. 

We might run in to the same kind of trouble as for the HashEmbedding class. If this is the case, I have to refactor out some of the properties.

**Comment by alanakbik** [comment]
Thanks! I'll merge and add your description to the docs!

**Comment by alanakbik** [comment]
:+1:

**Pull request merged**
