### PR TITLE
remove __init__ from tests

### PR DESCRIPTION
**Pull request by MSusik**
`__init__.py` in `tests` directory creates a situation where package `tests` is installed within `site-packages`.

Obviously, that causes problems if one wants to write his own tests in `tests` directory within his project and uses flair.

I suggest to remove the file. Then, setup.py will omit `tests` directory as it is no longer a package.

Additionally I added an entry in .gitignore that might be useful.

### CODE REVIEW

**Comment by alanakbik** [comment]
Thanks! Unfortunately, this seems to have broken the travis build. 

@tabergma any idea why the `__init__.py` is needed here?

**Comment by MSusik** [comment]
@alanakbik I will check if I can fix the build

**Comment by MSusik** [comment]
https://travis-ci.org/zalandoresearch/flair/builds/532794466 - this is the build for 6ad679c that passes

Why the succeeding builds don't pass is beyond my knowledge of the project. I can revert to 6ad679c if you want.

**Comment by alanakbik** [comment]
Your code looks good to me - I'll take a look at the travis error.

**Comment by tabergma** [comment]
`__init__.py` just marks `tests` as a package. If that is not wanted anymore, I guess we can remove it.

**Comment by alanakbik** [comment]
Hm the unit test that suddenly fails now also fails in other previously healthy PRs, but still passes locally. The specific test that fails downloads models from AWS and uses them, but times out. It may be that somehow travis cannot connect to AWS at the moment and times out. I'll try again later.

**Comment by alanakbik** [comment]
Hello @MSusik - I think the problem is caused by the new gitignore that includes the `regression_test` folder that the failing unit test requires. Could I ask you to comment out the test `test_trainer_results` in `test_text_regressor.py`? I'll fix this test later then.

**Comment by alanakbik** [comment]
:+1:

**Comment by MSusik** [comment]
OK, thanks for help!

**Comment by kashif** [comment]
👍

**Comment by alanakbik** [comment]
:+1:

**Comment by alanakbik** [comment]
@MSusik thanks for adding this!

**Pull request merged**
