### PR TITLE
GH-1156: PyTorch-Transformers -> Transformers

### PR DESCRIPTION
**Pull request by stefan-it**
Hi,

the latest version 2.0.0 of `transformers`, formerly known as `pytorch-transformers` and `pytorch-pretrained-bert`, has been released today 🎉

See changelog [here](https://github.com/huggingface/transformers/releases/tag/v2.0.0).

No breaking API changes.

This PR updates imports and documentation.

Flair-related improvements:
* [RoBERTa/GPT2 tokenization](https://github.com/huggingface/transformers/issues/1196)

### CODE REVIEW

**Comment by stefan-it** [comment]
I also ran `pytest --runslow tests/test_transformer_embeddings.py`, for executing the Transformer-related test cased: `6 passed, 3 warnings in 601.83s (0:10:01)`

**Comment by alanakbik** [comment]
Hey this is great! Thanks @stefan-it!!

**Comment by alanakbik** [comment]
:+1:

**Comment by yosipk** [comment]
👍

**Pull request merged**
