### PR TITLE
Remove BERT_PRETRAINED_MODEL_ARCHIVE_MAP check to support Custom models

### PR DESCRIPTION
**Pull request by adich23**

### CODE REVIEW

**Comment by adich23** [comment]
for Issue #554

**Comment by stefan-it** [comment]
In previous versions of `pytorch-pretrained-bert` this check was necessary, because when the model was not found, a confusing error message was thrown.

With the latest version, the following message is shown to the user:

```bash
2019-02-22 11:02:35,595 Model name 'bert---' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese). We assumed 'bert---' was a path or url but couldn't find any file associated to this path or url.
```

So I think we can remove the `BERT_PRETRAINED_MODEL_ARCHIVE_MAP` check here :)

**Comment by stefan-it** [comment]
:+1:

**Comment by alanakbik** [comment]
Cool, thanks!

**Comment by alanakbik** [comment]
:+1:

**Pull request merged**
