### PR TITLE
GH-923: add support for PyTorch's TensorBoard (ModelTrainer)

### PR DESCRIPTION
**Pull request by stefan-it**
Hi,

PyTorch 1.1.0 has native support for TensorBoard 🎉

This PR adds support for writing a TensorBoard compatible output, that looks like:

image

In order to use TensorBoard during training a model, just use:

```python
from flair.trainers import ModelTrainer

trainer: ModelTrainer = ModelTrainer(tagger, corpus, use_tensorboard=True)
```

All logs will be written to a local `./runs` folder.

Just install the latest `tensorboard` version (required to workaround [this refreshing bug](https://github.com/pytorch/pytorch/issues/20477)):

```bash
$ pip3 install tb-nightly
```

Then you can start TensorBoard with:

```bash
$ tensorboard --logdir runs
```

Finally, open `http://localhost:6006` in your webbrowser.

### CODE REVIEW

**Comment by alanakbik** [comment]
Hey this is great, thanks! We can probably add more structured output in the `ModelTrainer` so that more features of tensorboardX can be used. But we could already merge this PR and add more features in the future?

**Comment by stefan-it** [comment]
I think we can add other features later :)

**Comment by alanakbik** [comment]
:+1:

**Comment by yosipk** [comment]
👍

**Pull request merged**
