### PR TITLE
Allow to keep token embeddings after SequenceTagger.predict()

### PR DESCRIPTION
**Pull request by khituras**
This PR addresses #784. A new parameter `clear_word_embeddings` was added to `SequenceTagger.predict()` which is just connected through to `clear_embeddings` method that already has this parameter.
Since the embeddings are also cleared at the beginning of the `predict` method, there should be no issue with embeddings bleeding through the usage of multiple models on the same sentence/tokens.

I added a small test to show that the new parameter works as intended.

I hopy everything is fine with the PR, let me know!

### CODE REVIEW

**Comment by alanakbik** [comment]
@khituras the build was failing due to not passing the code formatting checks performed by black. I've corrected and hopefully it runs through now. Will merge then!

**Comment by khituras** [comment]
Aw, I forgot about that part, I meant to check via black myself. Sorry about that!

**Comment by alanakbik** [comment]
No worries - I'm actually thinking of perhaps removing the formatter again as it seems to be causing confusion.

**Comment by alanakbik** [comment]
:+1:

**Comment by yosipk** [comment]
:+1:

**Pull request merged**
