### PR TITLE
fix get_each_embedding when storage embedding is set to CPU

### PR DESCRIPTION
**Pull request by pommedeterresautee**
When run with CPU storage on a computer with CUDA / GPU, embeddings may not be on the right storage during training.

I don't know why, but it was not crashing on my own train task (French dataset)

`get_embedding` uses `get_each_embedding` now to get the same security.
`get_subembedding` has been deleted because it is not used in the project and would require to generalize get_embedding, implying more complexity.

The real issue I just realized is that Travis was not catching this bug because it doesn't run integration tests on GPU, and in this case it was a device storage issue. I don't know how to improve that.

### CODE REVIEW

**Comment by alanakbik** [comment]
@pommedeterresautee yes that's a good point on travis test not running on GPU. Before each release, I run manually on a GPU setup but of course that's not a great solution.

**Comment by alanakbik** [comment]
BTW this fix is now already part of #1145 right?

**Comment by pommedeterresautee** [comment]
Yes it is. I wanted to separate issues, but can't let a PR with a bug... so you got 2 times the same thing :-)

**Comment by pommedeterresautee** [comment]
Oh, do you have an issue with hyperparamter tests? I always had them and they don't appear on Travis. Never tried to dig.

**Comment by alanakbik** [comment]
For me the hyperparameter tests run through locally, though the hyperparameter selection module has not really been updated in a while and is more or less marked for replacement. We hope to find a better solution in the not too distant future to help users find good hyperparameters but are still looking into options.

**Pull request merged**
