### PR TITLE
GH-68 Bert update

### PR DESCRIPTION
**Pull request by kashif**
for issue #68

### CODE REVIEW

**Comment by stefan-it** [comment]
I think it should also be updated in `setup.py` :)

**Comment by kashif** [comment]
@stefan-it are you working on adding transformer-xl and openai-gpt embedding classes or should i do it?

**Comment by stefan-it** [comment]
@kashif I haven't started yet, so it would be great if you can add a kind of skeleton for both integrations, so that we can work together on it :)

**Comment by alanakbik** [comment]
:+1:

**Comment by stefan-it** [comment]
:+1:

**Comment by stefan-it** [comment]
@kashif *0.6.1* is out today. New release includes the new GPT-2 model :)

**Pull request closed without merging**
