### PR TITLE
readme: add references to new NAACL 2019 papers

### PR DESCRIPTION
**Pull request by stefan-it**
Hi,

this PR adds the following NAACL 2019 papers to the main readme:

* [Pooled Contextualized Embeddings for Named Entity Recognition](https://www.aclweb.org/anthology/papers/N/N19/N19-1078/)

* [FLAIR: An Easy-to-Use Framework for State-of-the-Art NLP](https://www.aclweb.org/anthology/papers/N/N19/N19-4010/)

### CODE REVIEW

**Comment by stefan-it** [comment]
Demo paper still needs to be added to the *Citing Flair* section. Maybe we can distinguish between "Flair embeddings" and "Flair" as the library itself 🤔

**Comment by alanakbik** [comment]
Thanks for adding this! Yes, we could ask for a citation of the COLING paper for Flair embeddings / NER results and for the demo for the Flair library. 

I'd also like to list paper references for all community contributions. For instance, your ACL paper on the multilingual language models for people who use the new language models. Perhaps an extra _citing flair_ page for this that lists all community contribution papers?

**Comment by alanakbik** [comment]
I'll merge this now and make a full citing flair page later!

**Comment by alanakbik** [comment]
:+1:

**Comment by yosipk** [comment]
👍

**Pull request merged**
