### PR TITLE
GH-507: make cache_root a global variable

### LINKED ISSUE #507: configurable CACHE_ROOT
It would be nice to make CACHE_ROOT configurable.
For example passing its value through environment variable:
`CACHE_ROOT = os.path.expanduser(os.getenv('FLAIR_CACHE_ROOT', '~/.flair'))`
instead of:
`CACHE_ROOT = os.path.expanduser(os.path.join('~', '.flair'))`
in file_utils.py

### LINKED ISSUE #653: Specify path for model?
The default is to cache models in <userhome>.flair/models   how can I specify the path where I want these cached?

Thanks
DB

### PR DESCRIPTION
**Pull request by alanakbik**
closes #507 
closes #653

You can now specify the base cache directory, i.e. the directory to where all models/embeddings/datasets get downloaded. It defaults to .flair in your home folder, but you can override this by calling 

```python
import flair
flair.cache_root = 'my/cache/directory'
```

before calling your code.

### CODE REVIEW

**Comment by stefan-it** [comment]
@alanakbik I think there's one missing `CACHE_ROOT`:

```bash
tests/test_data_fetchers.py
98:    shutil.rmtree(Path(flair.file_utils.CACHE_ROOT) / "datasets" / "ud_english")
```

**Comment by alanakbik** [comment]
@stefan-it thanks - just pushed the fix!

**Comment by kashif** [comment]
👍

**Comment by alanakbik** [comment]
:+1:

**Pull request merged**
