### PR TITLE
GH-680: rendering HTML with highlighted named entities

### PR DESCRIPTION
**Pull request by azeevg**
Added rendering HTML with highlighted entities. It's possible to override **colors** and **labels** of entities. One can also render part of html not wrapped by **body** and **html** tags - it can be useful when one needs to concatenate few htmls.

# Usage

    tagger = SequenceTagger.load('ner')

    sentence = Sentence(
        "Thibaut Pinot's challenge ended on Friday due to injury, and then Julian Alaphilippe saw "
        "his lead fall away. The BBC's Hugh Schofield in Paris reflects on 34 years of hurt."
    )

    tagger.predict(sentence)
    html = Visualizer.render_ner_html(sentence)

    with open("sentence.html", "w") as writer:
        writer.write(html)

**sentence.html**
image

Custom labels and colors could be used.

    # overriding color of PER, and changing ORG label to ORGANIZATION
    settings = {"colors": {"PER": "lightgreen"}, "labels": {"ORG": "Organization"}}
    html = Visualizer.render_ner_html(sentence, settings=settings)

image

If we want to integrate `html` into another web page, we could use `wrap_page` parameter to produce html without <html> and <body> tags wrapping it.

    sentence_1 = Sentence(
        "Thibaut Pinot's challenge ended on Friday due to injury, and then Julian Alaphilippe saw his lead fall away."
    )
    tagger.predict(sentence_1)

    sentence_2 = Sentence(
        "The BBC's Hugh Schofield in Paris reflects on 34 years of hurt."
    )
    tagger.predict(sentence_2)

    html_1 = Visualizer.render_ner_html(sentence_1, wrap_page=False)
    html_2 = Visualizer.render_ner_html(sentence_2, wrap_page=False)

    # no wrapping by <html> and <body>
    html = html_1 + " " + html_2

Now we can substitute `html` into any other html code.

    result = HTML_PAGE.format(text=html)

image

### CODE REVIEW

**Comment by azeevg** [comment]
Hi @alanakbik !
Do you understand why travis build fails? I tried **black --check .** locally, it works fine.

**Comment by alanakbik** [comment]
Looks like it's test_visual that is causing a black formatting error. I'll reformat!

**Comment by alanakbik** [comment]
@azeevg thanks for contributing this. Could you add a minimal full example code snippet on how to call this visualization method to this PR description? This will make it easier for other community members to use the new function!

**Comment by azeevg** [comment]
@alanakbik , I updated my first comment.

**Comment by alanakbik** [comment]
@azeevg thanks for adding this - looks great!

**Comment by alanakbik** [comment]
:+1:

**Comment by yosipk** [comment]
👍

**Comment by dcabo** [comment]
Seems like the rendering code [was moved to a new location](https://github.com/zalandoresearch/flair/commit/f9e22c847de695f968fb86b735d8b4813cd11114) just before the 4.3 release, so the code snippet should now be something like:

```
from flair.visual.ner_html import render_ner_html

tagger = SequenceTagger.load('ner')

sentence = Sentence(
    "Thibaut Pinot's challenge ended on Friday due to injury, and then Julian Alaphilippe saw "
    "his lead fall away. The BBC's Hugh Schofield in Paris reflects on 34 years of hurt."
)

tagger.predict(sentence)
html = render_ner_html(sentence)

with open("sentence.html", "w") as writer:
    writer.write(html)
```

**Comment by alanakbik** [comment]
@dcabo yes you're right, thanks for spotting this - just updated the release notes!

**Pull request merged**
