### PR TITLE
Add custom Bert model support

### PR DESCRIPTION
**Pull request by adich23**
for issue #493

### CODE REVIEW

**Comment by alanakbik** [comment]
Thanks for adding this - is there a custom model that I could test the code with?

**Comment by stefan-it** [comment]
@alanakbik You could try to use the BioBERT model, see this issue: https://github.com/huggingface/pytorch-pretrained-BERT/issues/239

But you have to manually convert the TensorFlow model to a PyTorch one :)

**Comment by adich23** [comment]
@alanakbik I tested it by downloaded the bert files separately and giving the directory path. But I think the Tenorflow model from BioBERT can also be used , since converting Tf model to Pytorch (https://github.com/huggingface/pytorch-pretrained-BERT/blob/master/pytorch_pretrained_bert/modeling.py#L52)  is already implemented by Hugging Face.

**Comment by alanakbik** [comment]
Ok great, thanks! I'll merge!

**Pull request merged**
