### PR TITLE
Fix #565 by raising an Exception for an empty String

### LINKED ISSUE #565: [BUG] A clear Exception/Error message must be thrown while trying to create a Sentence object from an empty string
**Describe the bug**
If one tries to create a `Sentence` object from an empty string, an `UnboundLocalError` of the `index` variable is thrown

**To Reproduce**
```python3
>>> from flair.data import Sentence
>>> s = ''
>>> Sentence(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\XYZ\AppData\Local\Programs\Python\Python36\lib\site-packages\flair\data.py", line 338, in __init__
    index += 1
UnboundLocalError: local variable 'index' referenced before assignment
```

**Expected behavior**
Something like `ValueError: Cannot create a Sentence object from an empty string` or some `Error` or `Exception` mentioning that the string is empty or a `Sentence object "" - 0 tokens`

**Environment (please complete the following information):**
   I feel this is applicable to any OS/version, but anyway:
 - Windows 10
 - flair-0.4.1
 - Python 3.6.8

### PR DESCRIPTION
**Pull request by Bharat123rox**
Fix #565 by raising a `ValueError` for an empty string.

### CODE REVIEW

**Comment by alanakbik** [comment]
Great, thanks for adding this!

**Comment by alanakbik** [comment]
:+1:

**Comment by stefan-it** [comment]
@Bharat123rox Thanks! Could you also add a small unit test for that case (=empty sentence)? That would be great :)

**Comment by alanakbik** [comment]
@stefan-it good point! Once the unit test is there, could you +1 and merge?

**Comment by stefan-it** [comment]
Sure, no problem :)

**Comment by Bharat123rox** [comment]
@stefan-it Should I add a separate function in `test_data.py` or under one of the `test_create_sentence_without_tokenizer()` or `test_create_sentence_with_tokenizer()` functions? Also, since I have to check for an exception, do I use
```python
with pytest.raises(ValueError) as e:
     assert(e.info) == "My error message"
```

if not, how do I go about ensuring that it raises the required error?

**Comment by Bharat123rox** [comment]
@stefan-it @alanakbik Will this be enough? How else should I test it?

**Comment by alanakbik** [comment]
Looks good to me! @kashif @MichaelHintz @stefan-it can one of you check, +1 and merge?

**Comment by Bharat123rox** [comment]
@alanakbik In case it looks good to you, please approve this PR, the approval seems to get reset on each new commit made.

**Comment by stefan-it** [comment]
:+1

**Comment by stefan-it** [comment]
:+1:

**Comment by kashif** [comment]
👍

**Comment by kashif** [comment]
thanks @Bharat123rox

**Comment by Bharat123rox** [comment]
thanks @kashif and @stefan-it for your patience

**Pull request merged**
