### PR TITLE
Optimize character to index conversion for a 4% decrease on CONNL 2003

### PR DESCRIPTION
**Pull request by pommedeterresautee**
Optimize the way padding is done by reducing the number of dictionary call.
Remove the conversion to UTF-8, and take care of old models in old format.
In the future, the conversion may be removed safely.

close https://github.com/zalandoresearch/flair/issues/1133
@alanakbik finally I did both, change in dictionary deserialization and change inside the class itself.

CONNL 2003 from 24s to 23s (-4%)
French dataset from 12s to 11s (-8%)

### CODE REVIEW

**Comment by pommedeterresautee** [comment]
There was strange issues because of dictionary conversion, so I finally made a small version of the optimization, keeping things like they are :-( May be to investigate in the future

**Comment by alanakbik** [comment]
Ah ok I was just measuring speed differences and finding they are roughly the same. Is this because of the last changes?

**Comment by pommedeterresautee** [comment]
Here I still have 23s and 11s for CONNL and French dataset. May be it's a less than 1 sec change but with rounding it appears bigger?

**Comment by alanakbik** [comment]
Ok great - looks good! Thanks for all your help!

**Comment by alanakbik** [comment]
:+1:

**Comment by yosipk** [comment]
👍

**Pull request merged**
