### PR TITLE
GH-772: unification for Persian (fa)

### PR DESCRIPTION
**Pull request by stefan-it**
Hi,

this PR addresses the unification issues raised in #722 for Persian :)

### CODE REVIEW

**Comment by stefan-it** [comment]
@alanakbik Could you rename the word embeddings files for Persian? E.g. `WordEmbeddings('fa')` is currently not possible:

```bash
>>> from flair.embeddings import WordEmbeddings
>>> embeddings = WordEmbeddings('fa')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stefan/Repositories/flair/flair/embeddings.py", line 250, in __init__
    cache_dir=cache_dir,
  File "/home/stefan/Repositories/flair/flair/file_utils.py", line 88, in cached_path
    return get_from_cache(url_or_filename, dataset_cache)
  File "/home/stefan/Repositories/flair/flair/file_utils.py", line 164, in get_from_cache
    f"HEAD request failed for url {url} with status code {response.status_code}."
OSError: HEAD request failed for url https://s3.eu-central-1.amazonaws.com/alan-nlp/resources/embeddings-v0.4/fa-wiki-fasttext-300d-1M.vectors.npy with status code 403.
```

**Comment by alanakbik** [comment]
@stefan-it just renamed the files! Sorry for the delay!

```python
embeddings = WordEmbeddings('fa')
embeddings_crawl = WordEmbeddings('fa-crawl')
```

should work now!

**Comment by alanakbik** [comment]
:+1:

**Comment by kashif** [comment]
👍

**Pull request merged**
