### PR TITLE
[NER] improve inference perf by > 40% on GPU when CRF is used

### PR DESCRIPTION
**Pull request by pommedeterresautee**
Viterbi seems to be the bottle neck of the inference part when GPU is used with CRF.

Here we simply move the computation of this part from GPU to CPU as the operations are not GPU optimized.
On my 2080TI with I7 (6 real cores), on the same data / same model, I went from 1mn 33s to 63 seconds inference time.
I have not made any test on other hardware but I expect perf improvement to be similar.

Moreover, this open the door to more optimizations as it removes the "lock" on GPU (we can easily do a better job at multithreading the process than Pytorch is currently doing), plus the same performance boost can probably be reproduced on the training part.

### CODE REVIEW

**Comment by pommedeterresautee** [comment]
I have made some tests to move the whole CRF part on the CPU (including for the training), keeping the featurisation on GPU, and it brings no improvement at all for the training part. 

I still think there are performance opportunities remaining as the GPU use is low and the inference is still not multithreaded at its best. 

One strategy I want to try now that the Viterbi part is on CPU is multithreading the process at the batch level. Right now the Viterbi algo is applied serially to each sentence, however the features are extracted by the GPU in batch. Before this PR there was a GPU lock, but now Viterbi is CPU only it should be doable to distribute the computation on each CPU core.

**Comment by alanakbik** [comment]
Hello @pommedeterresautee thanks a lot for this PR - we've unhappy with the performance of the CRF decoder for a while now so this really helps! I've run a test on CoNLL-03 predicting with the current 'ner' model on a v100 and prediction time decreases **from ~20 to ~15 seconds** on the evaluation dataset and **from ~95 to ~60 seconds** on all sentences in CoNLL-03. This is great! 

I'll run a few more tests on some other datasets to make sure that we get the same eval numbers and will merge into master!

**Comment by stefan-it** [comment]
Not directly related to this issue: but I've seen some F-Score mismatches between Flair output and the CoNLL script (maybe we can switch back to the conll script, or at least with a configurable parameter 🤔) But I'll collect some examples and open a new issue for that!

**Comment by alanakbik** [comment]
@stefan-it yes good point - Flair uses a slightly different logic to get from tokens to spans which should account for the difference. But this is something we've been meaning to add back in so it's good to put this back on the agenda.

**Comment by alanakbik** [comment]
@pommedeterresautee the following code is throwing an error: 

```python
tagger = SequenceTagger.load("frame-fast")
```

This likely affects pre-trained models that were trained without a CRF. I'll check into this a bit more.

**Comment by alanakbik** [comment]
I think the problem is that `self.transitions` is now always assumed to be there, but sometimes models are trained with `use_crf` set to `False`, which then throws an error. To reprodue: 

```python
tagger = SequenceTagger.load("frame-fast")
tagger.predict(Sentence("I love Berlin"))
```

@pommedeterresautee could you take a look?

**Comment by pommedeterresautee** [comment]
Tks, will check and fix.

**Comment by pommedeterresautee** [comment]
You were right about the error, self.transitions is the culprit, to remove the error it would require to retrain every model. The commit avoid such behaviour, now the matrix is created only when required.

**Comment by alanakbik** [comment]
Thanks! Looks good!

**Comment by alanakbik** [comment]
:+1:

**Comment by yosipk** [comment]
👍

**Pull request merged**
