### PR TITLE
GH-979: fixed UD_GERMAN_HDT paths

### LINKED ISSUE #979: UD_GERMAN_HDT corpus does not download
**Describe the bug**

When instantiating `UD_GERMAN_HDT()` corpus, the download of the train files fails because they have been renamed (and multiplied!).

Error is: 

```console
OSError: HEAD request failed for url https://raw.githubusercontent.com/UniversalDependencies/UD_German-HDT/dev/de_hdt-ud-train-a.conllu with status code 404.
```

**To Reproduce**

```python
from flair.datasets import UD_GERMAN_HDT

corpus = UD_GERMAN_HDT()
```

### PR DESCRIPTION
**Pull request by alanakbik**
Closes #979

### CODE REVIEW

**Comment by stefan-it** [comment]
Great, can confirm that it is working now :)

```bash
$ cd ~/.flair/datasets/ud_german_hdt/original/
$ cat *.conllu > all
$ cd ..
$ diff de_hdt-ud-train-all.conllu original/all
```

**Comment by stefan-it** [comment]
:+1:

**Comment by alanakbik** [comment]
:+1:

**Comment by alanakbik** [comment]
Cool, will train a POS model for German on this data to include with the upcoming release.

**Pull request merged**
