### PR TITLE
removed unused variables via SonarQube-7.6: Improving code quality from grade C to A.

### PR DESCRIPTION
**Pull request by pranjalsrajput**
All the 18 major bugs have been fixed, and the total remaining bugs detected in code quality tool ( SonarQube-7.6) are 0. Highest code quality i.e. Grade A is achieved.

### CODE REVIEW

**Comment by kashif** [comment]
@pranjalsrajput are these bugs or just un-used variables?

**Comment by pranjalsrajput** [comment]
These are actually un-used variables. But actually falls under the category of "Major bugs" in SonarQube, and because of these issues code quality grade was "C". Solving all of them has improved grade to "A".

**Comment by kashif** [comment]
can you delete instead of commenting out the 2 variables? thanks!

**Comment by pranjalsrajput** [comment]
Sorry about that. Now, it's been removed from the two files.

**Comment by kashif** [comment]
:+1:

**Comment by alanakbik** [comment]
:+1:

**Comment by alanakbik** [comment]
Thanks!

**Pull request merged**
