### PR TITLE
Enhancement to Plotter() visualization

### PR DESCRIPTION
**Pull request by SiewLinYap**
1 enable plots to be displayed when running in both .py and .ipynb
2 display text to notify user the path of the saved plots

Screenshot 2019-08-01 at 2 31 24 PM

### CODE REVIEW

**Comment by alanakbik** [comment]
@SiewLinYap thanks for adding this. Looks like the build is failing because `IPython` is not found. Could you add the from `IPython` dependency to `requirements.txt` and push an update?

**Comment by alanakbik** [comment]
Thanks!

**Comment by alanakbik** [comment]
:+1:

**Comment by yosipk** [comment]
👍

**Pull request merged**
