### PR TITLE
A simple method to print the tag transition matrix learned by the CRF

### PR DESCRIPTION
**Pull request by davidsbatista**
- added `get_transition_matrix` to the `SequenceTagger` model
- added `tabulate` dependency to requirements.txt

### CODE REVIEW

**Comment by alanakbik** [comment]
Thanks! can you also add the dependency to `setup.py`?

**Comment by davidsbatista** [comment]
ah sure!, always forget that one.

**Comment by davidsbatista** [comment]
@alanakbik any idea what might caused this message:

> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
> Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
> The build has been terminated

**Comment by alanakbik** [comment]
@davidsbatista I don't think this has anything to do with your PR. This test downloads models from AWS and suddenly started failing. Likely travis cannot download large models from AWS at the moment, so I'm hoping the error is only temporary. If not, we might need to remove unit tests that download large models.

**Comment by davidsbatista** [comment]
achso! ok, so I guess we just leave this open, and triggered the build/tests once the issue is fixed?

**Comment by alanakbik** [comment]
Yeah I would leave it open - I'll try running the tests again tomorrow. If it doesn't work then, I'll modify the unit test so that it does not download large models.

**Comment by davidsbatista** [comment]
okies, thanks :+1:

**Comment by alanakbik** [comment]
:+1:

**Comment by kashif** [comment]
👍

**Comment by alanakbik** [comment]
@davidsbatista thanks for adding this!

**Comment by davidsbatista** [comment]
gerne!

**Pull request merged**
