### PR TITLE
added the max_tokens_per_doc param to the load_classification_corpus

### PR DESCRIPTION
**Pull request by GiliGoldin**
Added the max_tokens_per_doc parameter to the 'load_classification_corpus' function.
Fixed documentation regarding this parameter in the 'read_text_classification_file' function according to the real functionality.

### CODE REVIEW

**Comment by alanakbik** [comment]
Hello @GiliGoldin - thanks for adding this!

**Comment by alanakbik** [comment]
:+1:

**Comment by kashif** [comment]
👍

**Comment by alanakbik** [comment]
Thanks!

**Pull request merged**
